### ISSUE TITLE
Roster Removal email contains Ben Gustafson DATM should be Raaj 

### ISSUE THREAD

**Issue by zdv-pipeline** [kzdv/info#7]
Issue created by Raaj P. - RP | DATM (Raaj Patel): Roster Removal email contains Ben Gustafson DATM should be Raaj Patel DATM

**Comment by Raajheer1** [comment]
https://cdn.discordapp.com/attachments/859486729945743380/1011363221355106445/IMG_5428.png

**Comment by dhawton** [comment]
Fixed in https://github.com/kzdv/zdv-website/commit/cba744bd46dd13acbd7618eeda241d4faab360fd, deployed to cluster.
